### ISSUE TITLE
A configured GitHub token raises TypeError: GitHubProvider has no _token field (sibling of PFactory#365)

### ISSUE THREAD

**Issue by olafkfreund** [olafkfreund/TFactory#829]
Found by grepping TFactory for the call shape after revendor-pf reported the same defect in PFactory (PFactory#365). TFactory has it too, at two sites.

## The bug

Both consumers of the vendored git-provider layer build the GitHub provider by passing the tenant token as `_token=`:

- `apps/web-server/server/routes/github.py:656`
- `apps/web-server/server/services/auto_fix_service.py:244`

```python
# Default to github
kwargs = {}
if project_path:
    kwargs["_project_dir"] = project_path
# Pass token if present
if token:
    kwargs["_token"] = token
return get_provider(ProviderType.GITHUB, repo=repo_name, **kwargs)
```

`GitHubProvider` has no such field. Its dataclass attributes are `_repo`, `_gh_client`, `_project_dir`, `enable_rate_limiting` — it authenticates through the `gh` CLI, not a passed token. `get_provider` forwards `**kwargs` straight to the constructor, so the call raises.

Demonstrated, not inferred:

```
$ python3 -c "..."
TypeError: GitHubProvider.__init__() got an unexpected keyword argument '_token'
```

## Reachability

The `_token` key is only added `if token:`, and `token` is `settings.get("gitToken")`. So:

- Project with **no** `gitToken` configured -> works (falls through to `gh` CLI auth)
- Project **with** a `gitToken` configured -> `TypeError`, every time

Configuring a GitHub token — the one action a user would take to make GitHub auth work — is exactly what breaks it. That is why it has gone unnoticed: the default path is the working one.

This has always been true; it is not a regression from the re-vendor in #828. `GitHubProvider` has no `_token` field at `32d1f3a2`, `8f15849c`, `729aaab2` or `59f9f76f`.

## Not the same as the GitLab/Azure branches

Worth stating explicitly, because the surrounding code looks identical and is fine:

```python
kwargs["_token"] = token   # GitLab  -> valid, GitLabProvider._token exists
kwargs["_pat"]   = token   # Azure   -> valid, AzureDevOpsProvider._pat exists
kwargs["_token"] = token   # GitHub  -> TypeError
```

`routes/github.py:628` and `auto_fix_service.py:224` are the GitLab sites and are correct. Only `:656` and `:244` are broken.

## Fix depends on Factory#370

Do not "fix" this by dropping the token — that would silently ignore a configured credential, which is worse than failing loudly. The real fix arrives with Factory#370 (hub #390), which adds a token-authenticated `HttpGitHubProvider` to the canonical: at hub SHA `729aaab2` and later, `get_provider(..., token=...)` returns `HttpGitHubProvider` instead. So the fix is:

1. Re-vendor onto a hub SHA that includes Factory#370 (`729aaab2` or later — note this grows the canonical from 8 files to 10, see below)
2. Change both GitHub-branch sites from `kwargs["_token"] = token` to `kwargs["token"] = token`
3. Add a regression test that constructs the GitHub provider **with** a token, since the current suite only ever exercises the no-token path

## Related

- PFactory#365 — same defect, same `routes/github.py` call shape
- TFactory#828 — the in-flight re-vendor (targets `8f15849c`, which predates Factory#370 and therefore does not fix this)
- Factory#370 / hub #390 — adds the token-authenticated provider that makes this fixable
- Factory#394 — canonical defects to batch into the next fleet SHA bump

**Comment by olafkfreund** [comment]
Sharpening the "do not fix this by dropping the token" warning, because the consequence is more specific than the original wording conveyed (credit to revendor-pf, working the PFactory#365 side).

`GitHubProvider` authenticates through the `gh` CLI, which resolves its identity from the ambient environment — `GH_TOKEN`/`GITHUB_TOKEN`, or the `gh` credential store in the pod. So if someone "fixes" the `TypeError` by deleting the `_token` line:

- The request does not fail. It **succeeds**, as whatever ambient `gh` identity the pod happens to hold.
- A tenant who configured `gitToken` specifically to scope their access gets silently upgraded or downgraded to the pod's identity instead.
- In a multi-tenant deployment that is tenant A's request running under a shared or another tenant's credential, with nothing in the logs to indicate the configured token was ignored.

That is strictly worse than the current behaviour. The `TypeError` is loud, immediate, and impossible to misread. A silent identity substitution is none of those and would likely go unnoticed for as long as this bug has.

So the acceptable fixes are only:

1. **Preferred** — re-vendor onto a hub SHA carrying Factory#370 and pass `token=`, so the tenant credential is genuinely used via `HttpGitHubProvider`.
2. **Stopgap** — if a configured `gitToken` cannot yet be honoured on the GitHub path, raise an explicit error naming the reason. Still fails, but with a message that says *why* rather than surfacing a constructor `TypeError`.

Deleting the line is not on that list.

This also sets the bar for the regression test: asserting "constructing with a token does not raise" is not sufficient, since dropping the line satisfies it. The test has to assert the token is actually **in effect** on the returned provider — otherwise it green-lights precisely the wrong fix.

**Comment by olafkfreund** [comment]
Two additions that make this a fix rather than a bug report. Both found by sweeping the other three services; full write-up in AIFactory#1043.

## 1. The fix already exists and is proven

CFactory does not have this bug. It hit the same problem and solved it with its own httpx-based GitHub provider — `apps/backend/cfactory/git_providers.py:169`, `HttpGitHubProvider`, **local to CFactory, not vendored** — constructed directly with the token instead of going through `get_provider`. Its module docstring states outright that `gh` is deliberately not used, so there is no ambient-auth path to defend.

Factory#370 (hub #390) upstreamed exactly that into the canonical as `providers/http_github_provider.py`. So the work here is "re-vendor and change one kwarg", not "design a fix".

## 2. The ambient-substitution risk already happened once

CFactory wrote a regression test for it — `tests/test_git_providers.py:209`:

```python
@pytest.mark.parametrize("ambient", ["GITHUB_TOKEN", "GH_TOKEN"])
def test_an_ambient_gh_login_does_not_switch_issue_writing_on(monkeypatch, ambient):
    """The credential that opens issues in someone's repo must be *chosen*.

    ``gh auth login`` leaves these in the environment of every developer machine
    and CI runner; inheriting one would turn the board's issue-writing on by
    accident, which is exactly what happened the first time this was wired.
    """
```

"Exactly what happened the first time this was wired." The silent identity substitution described in the comment above is a repeat of a real incident, not a theoretical concern. It parametrizes over both `GITHUB_TOKEN` and `GH_TOKEN`, since `gh auth login` leaves both around.

Note this is a pattern to adapt, not a file to copy — CFactory asserts on `github_sync.sync_enabled(...)`, a board-sync gate with no equivalent here. The analogous assertion for TFactory is on provider construction: given an ambient `GITHUB_TOKEN`/`GH_TOKEN` and a tenant that configured its own `gitToken`, the provider built must use the tenant's token.

## Fleet status

| service | has the bug | notes |
|---|---|---|
| CFactory | no | local `HttpGitHubProvider`; origin of the canonical fix |
| PFactory | yes | PFactory#365 |
| **TFactory** | **yes** | this issue |
| AIFactory | yes | AIFactory#1043 |

Three services, same defect, same two file shapes, GitHub branch only. One bug copied three times, not three independent ones — best fixed as a single coordinated change after the canonical bump rather than by three people separately.

One sequencing warning: step 1 of the fix (re-vendor onto a SHA carrying Factory#370) grows the canonical from 8 files to 10, and per Factory#394 the drift checker's hardcoded file list does not notice a short-vendored tree — it reports green on a package that cannot be imported. Those two issues interact, so whoever does this needs both facts at once.

**Comment by olafkfreund** [comment]
Last piece of evidence, and it makes the ambient-substitution assertion concrete for this repo specifically rather than inherited from CFactory's incident.

TFactory already reads ambient `GH_TOKEN` / `GITHUB_TOKEN` in its own code, in two places that matter:

**`apps/backend/core/mcp_credentials.py:111-119`** — the same fallback chain PFactory has:

```python
token_env = op.get("tokenEnv") or "GITHUB_TOKEN"
token = _resolve_env(token_env)
...
for fallback in ("GITHUB_PERSONAL_ACCESS_TOKEN", "GH_TOKEN"):
```

**`apps/backend/tools/git_writer.py:372-377`** — and this one is the sharper case, because it is a *write* path that uses an ambient credential deliberately:

```python
# Authenticate the push via gh's credential helper (scoped to this one
# command, no global git-config mutation). gh reads the token from its
# own env (GH_TOKEN/GITHUB_TOKEN) — the same credential the pr_comment
# path already uses — so no secret ever touches argv (cf. env-not-argv).
```

That is intentional and correct in context — it is a deliberate, documented design decision for the verify Job's push path.

But it is exactly why assertion 2 is not theoretical here. If someone "fixes" this issue by dropping the `_token` line and letting `GitHubProvider` fall through to ambient `gh` auth, the result would **match an established, intentional pattern in this codebase** and read as correct in review. There is a documented precedent for "gh reads the token from its own env" being the right answer — in a different subsystem, for a different purpose, where no tenant credential is in play.

The distinction the reviewer has to hold is: ambient auth is fine where there is no tenant credential to honour (git_writer's ephemeral verify Job push), and wrong where a tenant explicitly configured `gitToken` and expects *that* identity to be used. The provider path is the second case.

So the regression test is not defending against an unlikely mistake. It is defending against the most natural-looking fix available, in a repo that already contains a sanctioned example of the pattern.

That closes the evidence chain on this issue:
- the bug (demonstrated `TypeError`, two sites)
- the fix already written and proven (CFactory's `HttpGitHubProvider`, canonicalised by Factory#370)
- the wrong fix, measured (drop the line -> no raise, wrong class, token not in effect)
- the wrong fix already having happened once in this fleet (CFactory's test docstring)
- and now, the wrong fix having a sanctioned-looking precedent in *this* repo
